<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Gen2: Systematic Feature Engineering – Tzu-Yuan</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-c1fac2584b48ed01fb6e278e36375074.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="styles.scss">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Tzu-Yuan</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bs-of-am" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">BS of AM</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-bs-of-am">    
        <li>
    <a class="dropdown-item" href="./AM.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./AM_thesis.html">
 <span class="dropdown-text">Quantum Bayesian Inference</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ms-of-dsic" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">MS of DSIC</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ms-of-dsic">    
        <li>
    <a class="dropdown-item" href="./DSIC.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ML.html#assignments">
 <span class="dropdown-text">ML &amp; Data Science</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./DL.html#assignments">
 <span class="dropdown-text">Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./BigData.html#assignments">
 <span class="dropdown-text">Big Data Analysis</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./DataAnalysis.html#assignments">
 <span class="dropdown-text">Data Analysis Math</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ms-of-sdar" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">MS of SDAR</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ms-of-sdar">    
        <li>
    <a class="dropdown-item" href="./SDAR.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./GISPY.html#assignments">
 <span class="dropdown-text">GIS &amp; Python</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EPPS6356.html#assignments">
 <span class="dropdown-text">Data Visualization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./EPPS6354.html">
 <span class="dropdown-text">Information Management</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./CV.html"> 
<span class="menu-text">CV</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
        
    </div>
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Gen2: Systematic Feature Engineering</h1>
<p class="subtitle lead">AA DFW Hub | 804,728 flights | V1–V12 x 12 versions x 9 experiments = 108 experiments</p>
</div>



<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<nav style="margin-bottom:1.5rem;">
  <small><a href="index.html">Home</a> › <a href="research-overview-en.html">Research Overview</a> › Gen2</small>
  <br>
  <a href="research-overview-en.html" style="display:inline-block;margin-top:0.5rem;padding:0.3rem 0.8rem;border:1px solid #ccc;border-radius:4px;text-decoration:none;font-size:0.9rem;">← Back to Research Overview</a>
</nav>
<hr>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Overview</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">V1 Baseline</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false">V2 Literature Features</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false">V3–V5 Same-Source Re-encoding Failures</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-5-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-5" role="tab" aria-controls="tabset-1-5" aria-selected="false">V6 SHAP + Optuna</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-6-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-6" role="tab" aria-controls="tabset-1-6" aria-selected="false">V7–V8 Feature Redundancy Failures</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-7-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-7" role="tab" aria-controls="tabset-1-7" aria-selected="false">V9 TAF Weather Forecasts</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-8-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-8" role="tab" aria-controls="tabset-1-8" aria-selected="false">V10–V12 All Negative</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-9-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-9" role="tab" aria-controls="tabset-1-9" aria-selected="false">V9c Finalized</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-10-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-10" role="tab" aria-controls="tabset-1-10" aria-selected="false">Phase 1–4 Comprehensive Analysis</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<section id="core-design-principles" class="level3">
<h3 class="anchored" data-anchor-id="core-design-principles">Core Design Principles</h3>
<p>Gen1’s ETD leakage forced a complete restart. Gen2’s core question became:</p>
<blockquote class="blockquote">
<p><strong>Under strict pre-departure leakage control, which features truly have predictive power?</strong></p>
</blockquote>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Core Finding (across 12 versions): Only genuinely new external information can improve AUC; same-source re-encoding is universally ineffective.</strong></p>
</div>
</div>
</section>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset">Dataset</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Item</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Data Source</td>
<td>American Airlines Snowflake Database</td>
</tr>
<tr class="even">
<td>Scope</td>
<td>DFW Hub departures</td>
</tr>
<tr class="odd">
<td>Total Flights</td>
<td>804,728</td>
</tr>
<tr class="even">
<td>Delay Rate</td>
<td>23.3% (arrival delay ≥ 15 min)</td>
</tr>
<tr class="odd">
<td>Train</td>
<td>2021–2022</td>
</tr>
<tr class="even">
<td>Val</td>
<td>2023 H1</td>
</tr>
<tr class="odd">
<td>Test</td>
<td>2023 H2</td>
</tr>
</tbody>
</table>
</section>
<section id="experiment-matrix" class="level3">
<h3 class="anchored" data-anchor-id="experiment-matrix">Experiment Matrix</h3>
<p>Each version (V1–V12) was evaluated across 3 feature sets x 3 models = <strong>9 experiments</strong>, totaling <strong>108 experiments</strong> across 12 versions.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature Set</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clean</td>
<td>Schedule + calendar only (cleanest baseline)</td>
</tr>
<tr class="even">
<td>T-24h</td>
<td>+ tail chain + weather + external (available 24h prior)</td>
</tr>
<tr class="odd">
<td>T-2h</td>
<td>+ real-time weather snapshot (2h before departure)</td>
</tr>
<tr class="even">
<td>T-2h+Enhanced</td>
<td>+ literature-inspired advanced features</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Random Forest</td>
<td>Baseline ensemble</td>
</tr>
<tr class="even">
<td>XGBoost</td>
<td>Primary GBDT model</td>
</tr>
<tr class="odd">
<td>XGBoost + CatBoost</td>
<td>Ensemble method</td>
</tr>
</tbody>
</table>
</section>
<section id="version-auc-summary" class="level3">
<h3 class="anchored" data-anchor-id="version-auc-summary">12-Version AUC Summary</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Version</th>
<th>Best AUC</th>
<th>vs Previous</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>V1</td>
<td>0.7623</td>
<td>—</td>
<td>Baseline (with ETD, later deprecated)</td>
</tr>
<tr class="even">
<td><strong>V2</strong></td>
<td><strong>0.7352</strong></td>
<td>—</td>
<td>✅ Removed ETD, literature features</td>
</tr>
<tr class="odd">
<td>V3</td>
<td>0.7357</td>
<td>+0.0005</td>
<td>⚪ Two-stage slightly positive but marginal</td>
</tr>
<tr class="even">
<td>V4</td>
<td>0.7373</td>
<td>+0.0021</td>
<td>✅ Dest METAR positive</td>
</tr>
<tr class="odd">
<td>V5</td>
<td>0.7355</td>
<td>−0.0018</td>
<td>❌ BTS monthly statistics</td>
</tr>
<tr class="even">
<td><strong>V6</strong></td>
<td><strong>0.7420</strong></td>
<td>+0.0047</td>
<td>✅ SHAP selection + Optuna</td>
</tr>
<tr class="odd">
<td>V7</td>
<td>0.7366</td>
<td>−0.0054</td>
<td>❌ Temporal/route features</td>
</tr>
<tr class="even">
<td>V8</td>
<td>0.7407</td>
<td>−0.0013</td>
<td>❌ SHAP interaction + Focal Loss</td>
</tr>
<tr class="odd">
<td><strong>V9</strong></td>
<td><strong>0.7440</strong></td>
<td>+0.0020</td>
<td>✅ TAF weather forecasts</td>
</tr>
<tr class="even">
<td>V10</td>
<td>0.7429</td>
<td>−0.0011</td>
<td>❌ Target Encoding + network weather</td>
</tr>
<tr class="odd">
<td>V11</td>
<td>0.7414</td>
<td>−0.0026</td>
<td>❌ NOTEARS DAG + Stacking</td>
</tr>
<tr class="even">
<td>V12</td>
<td>0.7423</td>
<td>−0.0017</td>
<td>❌ Delay Absorption meta-feature</td>
</tr>
</tbody>
</table>
<hr>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<section id="design" class="level3">
<h3 class="anchored" data-anchor-id="design">Design</h3>
<p>V1 includes three feature categories with strict temporal splitting (but retains ETD for comparison):</p>
<ul>
<li><strong>Schedule + Calendar</strong>: Departure month, day of week, time period, route</li>
<li><strong>Tail Chain</strong>: Previous flight delay (simple one-hop)</li>
<li><strong>DFW METAR Weather</strong>: Real-time weather observation at T-2h</li>
<li><strong>ETD Snapshot</strong> (T-2h+ETD version): Airline operations system’s estimated departure time deviation</li>
</ul>
<p>Literature references: Zhou (2025) AUC=0.898, Berkeley (2025) F1=62.9%, Chen (2019) Tail chain, Qu (2023) CNN-MLSTM</p>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>V1 Best (T-2h+ETD + XGBoost): AUC = 0.7623, F1 = 0.5031</strong></p>
</div>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature Set</th>
<th>Best AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clean (schedule + calendar)</td>
<td>0.6226</td>
</tr>
<tr class="even">
<td>T-24h (+ tail chain + weather)</td>
<td>~0.70</td>
</tr>
<tr class="odd">
<td>T-2h (+ real-time weather)</td>
<td>~0.72</td>
</tr>
<tr class="even">
<td>T-2h+ETD (+ operations snapshot)</td>
<td><strong>0.7623</strong></td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V1’s ETD Problem</strong>: The high AUC of the T-2h+ETD version comes from ETD deviation directly reflecting delay status. Same fatal leakage as Gen1. ETD removed from V2 onward.</p>
</div>
</div>
</section>
<section id="key-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="key-conclusions">Key Conclusions</h3>
<ul>
<li>XGBoost outperforms RF and DNN across all feature versions</li>
<li>Tail chain (previous flight delay) contributed the largest AUC improvement in T-24h version</li>
<li>Deep learning (DNN) does not outperform tree-based models on tabular data</li>
</ul>
<hr>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<section id="design-1" class="level3">
<h3 class="anchored" data-anchor-id="design-1">Design</h3>
<p>Removed ETD, added 9 literature-validated original features:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 39%">
<col style="width: 26%">
<col style="width: 34%">
</colgroup>
<thead>
<tr class="header">
<th>Feature Group</th>
<th>Features</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Multi-hop Tail Chain</td>
<td>prev_2/3_flight_delay, tail_chain_cumul_delay</td>
<td>Previous 2, 3 flight cumulative delays</td>
</tr>
<tr class="even">
<td>Airport Congestion</td>
<td>dfw_dep_count_1h, dfw_avg_delay_3h, dfw_delay_rate_3h</td>
<td>DFW real-time congestion metrics</td>
</tr>
<tr class="odd">
<td>Weather Severity</td>
<td>wx_severity</td>
<td>Composite weather severity index</td>
</tr>
<tr class="even">
<td>Turnaround Pressure</td>
<td>turnaround_pressure, prev_flight_landed</td>
<td>Turnaround pressure</td>
</tr>
</tbody>
</table>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V2 Best (T-2h+Enhanced + XGBoost): AUC = 0.7352</strong></p>
<p>T-2h+Enhanced vs T-2h baseline: <strong>+0.0176</strong> (largest single feature engineering improvement across 12 versions)</p>
</div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature Set</th>
<th>V2 AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clean</td>
<td>~0.62</td>
</tr>
<tr class="even">
<td>T-24h</td>
<td>~0.70</td>
</tr>
<tr class="odd">
<td>T-2h</td>
<td>0.7176</td>
</tr>
<tr class="even">
<td>T-2h+Enhanced</td>
<td><strong>0.7352</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="why-v2-is-an-important-milestone" class="level3">
<h3 class="anchored" data-anchor-id="why-v2-is-an-important-milestone">Why V2 is an Important Milestone</h3>
<p>This is the only case where “same-source but literature-validated feature engineering” produced a significant improvement. Subsequent versions repeatedly confirmed: <strong>only genuinely new external information can break the AUC ceiling</strong>. V2’s 9 features are a borderline case (manually designed features with strong literature support).</p>
<hr>
</section>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<section id="v3-two-stage-departure-delay-prediction" class="level3">
<h3 class="anchored" data-anchor-id="v3-two-stage-departure-delay-prediction">V3: Two-Stage Departure Delay Prediction</h3>
<p><strong>Design</strong>: Stage I uses XGBoost regressor to predict departure delay, Stage II adds the prediction as a feature for arrival delay prediction.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Stage I R² only 0.05–0.18</strong>, insufficient prediction quality to support Stage II</p>
<p>Stage I root cause: Most departure delay variance comes from events after T-2h (ground delays, ATC directives, sudden weather), which are unknowable at T-2h.</p>
</div>
</div>
<p>V3 best AUC = 0.7357 (T-2h+Enhanced + RF), <strong>only +0.0005 above V2</strong>, practically meaningless.</p>
<p><strong>First pattern confirmation</strong>: Same-source meta-features are ineffective.</p>
<hr>
</section>
<section id="v4-destination-airport-metar-weather-11-features" class="level3">
<h3 class="anchored" data-anchor-id="v4-destination-airport-metar-weather-11-features">V4: Destination Airport METAR Weather (11 features)</h3>
<p><strong>Design</strong>: Added NOAA IEM ASOS/METAR observations from 277 destination airports (T-2h).</p>
<p>New features: dest_wx_temp_f, wind_speed_kt, wind_gust_kt, visibility_mi, precip_1hr_in, ceiling_ft, has_thunder, has_fog, has_snow, pressure_hpa, wx_severity</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>V4 Best AUC = 0.7373 (T-2h+Enhanced + XGBoost)</strong>, vs V2’s 0.7352, <strong>+0.0021</strong></p>
</div>
</div>
</div>
<p>Positive but marginal. Reason: T-2h destination weather snapshot is a single time-point observation, unable to capture in-flight weather dynamics.</p>
<hr>
</section>
<section id="v5-bts-monthly-airport-statistics-6-features" class="level3">
<h3 class="anchored" data-anchor-id="v5-bts-monthly-airport-statistics-6-features">V5: BTS Monthly Airport Statistics (6 features)</h3>
<p><strong>Design</strong>: Added BTS destination airport monthly statistics (delay rate, avg delay, delay std dev, for both origin/dest).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V5 Best AUC = 0.7355 (−0.0018 vs V4) — negative result</strong></p>
<p>Monthly granularity is too coarse for individual flight prediction; dest_airport_encoded already implicitly captures airport-level delay tendencies. Coverage: 204/286 destination airports (71.3%), 724,660 flights (90.1%).</p>
</div>
</div>
<p><strong>Second pattern confirmation</strong>: Coarse-grained same-source information is ineffective.</p>
<hr>
</section>
</div>
<div id="tabset-1-5" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-5-tab">
<section id="design-2" class="level3">
<h3 class="anchored" data-anchor-id="design-2">Design</h3>
<p>V6 builds on V4 (then-best AUC=0.7373) with two optimization steps:</p>
<p><strong>Step 1: SHAP Backward Elimination</strong></p>
<p>Removed 14 low-contribution features from T-2h+Enhanced, including: dfw_avg_aadt, wx_has_snow, dest_wx_has_snow, prev_flight_landed, dest_wx_has_fog, dest_wx_has_thunder, is_weekend, dest_wx_visibility_mi, dest_wx_wind_gust_kt, prev_flight_delayed_15, wx_has_fog, dest_is_international, wx_visibility_mi, is_holiday</p>
<p><strong>Step 2: Optuna Bayesian HPO (100 trials)</strong></p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Optuna Best Val AUC = 0.7541</strong> | Search time: 2310 seconds (38.5 minutes)</p>
<p>Best hyperparameters (XGBoost): learning_rate = 0.006, max_depth = 10, gamma = 4.79, colsample_bytree = 0.33</p>
</div>
</div>
</div>
</section>
<section id="results-2" class="level3">
<h3 class="anchored" data-anchor-id="results-2">Results</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V6 Best AUC = 0.7420 (T-2h+Enhanced + XGBoost)</strong>, vs V4’s 0.7373, <strong>+0.0047</strong></p>
</div>
</div>
<p>Literature: Borboudakis &amp; Tsamardinos (arXiv:2410.06815) — SHAP backward elimination; Akiba et al.&nbsp;(2019) Optuna; Bergstra et al.&nbsp;(2011) HPO</p>
<p><strong>V6 became the baseline for all subsequent versions.</strong></p>
<hr>
</section>
</div>
<div id="tabset-1-6" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-6-tab">
<section id="v7-temporal-route-features-8-new-features" class="level3">
<h3 class="anchored" data-anchor-id="v7-temporal-route-features-8-new-features">V7: Temporal + Route Features (8 new features)</h3>
<p>Added: dest_delay_rate_7d/30d, route_daily_freq, aircraft_legs_today, dfw_delay_rate_1h/6h</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V7 Best AUC = 0.7366 (T-2h+Enhanced + XGB+CatBoost)</strong>, vs V6’s 0.7420, <strong>−0.0054</strong></p>
<p>Worst single-version regression across 12 versions.</p>
<p>Root cause: XGBoost with depth=10 already captures these temporal patterns automatically; all 8 new features are redundant. V6’s colsample_bytree=0.33 was not re-optimized for new features.</p>
</div>
</div>
<hr>
</section>
<section id="v8-shap-interaction-features-focal-loss" class="level3">
<h3 class="anchored" data-anchor-id="v8-shap-interaction-features-focal-loss">V8: SHAP Interaction Features + Focal Loss</h3>
<p><strong>Two attempts</strong>: 1. SHAP interaction features (15, e.g., dep_hour × wx_severity) 2. Focal Loss for class imbalance (positive rate 23.3%)</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V8 Best AUC = 0.7407</strong>, both negative</p>
<p>SHAP interactions: depth=10 already implicitly captures interaction effects; manual addition is redundant. Focal Loss: At 23.3% imbalance, it trades AUC for F1 (F1 improved to 0.4744, but AUC decreased).</p>
</div>
</div>
<p><strong>V7 and V8 consecutive negative results confirm: AUC ≈ 0.74 is the current feature space ceiling. Entirely new external information is needed to break through.</strong></p>
<hr>
</section>
</div>
<div id="tabset-1-7" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-7-tab">
<section id="design-3" class="level3">
<h3 class="anchored" data-anchor-id="design-3">Design</h3>
<p>V9 introduces <strong>TAF (Terminal Aerodrome Forecast)</strong> weather forecast data — fundamentally different from V4 METAR “observations”: TAF forecasts “future weather conditions at arrival time.”</p>
<p>Data source: Iowa Environmental Mesonet (IEM) public archive, 212 airports (covering 89.9% of destinations)</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>Coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>taf_dest_wind_kt</td>
<td>76.8%</td>
</tr>
<tr class="even">
<td>taf_dest_gust_kt</td>
<td>76.8%</td>
</tr>
<tr class="odd">
<td>taf_dest_visibility_mi</td>
<td>85.6%</td>
</tr>
<tr class="even">
<td>taf_dest_ceiling_ft</td>
<td>35.6%</td>
</tr>
<tr class="odd">
<td>taf_dest_has_precip</td>
<td>85.6%</td>
</tr>
<tr class="even">
<td>taf_dfw_wind_kt</td>
<td>93.3%</td>
</tr>
<tr class="odd">
<td>taf_dfw_ceiling_ft</td>
<td>38.9%</td>
</tr>
<tr class="even">
<td>taf_dest_ceil_delta</td>
<td>35.6%</td>
</tr>
<tr class="odd">
<td>taf_severity</td>
<td>100.0%</td>
</tr>
</tbody>
</table>
</section>
<section id="results-3" class="level3">
<h3 class="anchored" data-anchor-id="results-3">Results</h3>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V9 Best AUC = 0.7440 (T-2h+Enhanced + XGBoost)</strong>, vs V6’s 0.7420, <strong>+0.0020</strong></p>
<p>Broke the V7–V8 negative streak.</p>
</div>
</div>
</section>
<section id="why-taf-works-but-metar-is-limited" class="level3">
<h3 class="anchored" data-anchor-id="why-taf-works-but-metar-is-limited">Why TAF Works but METAR is Limited</h3>
<p>TAF is a forecast system output of “future weather prediction,” reflecting expected weather conditions at the arrival time window even at T-2h prediction time; METAR is only “current weather observation,” with limited representativeness for destination weather on long-haul flights (flight time &gt; 2 hours).</p>
<p><strong>Pattern confirmed again</strong>: Only genuinely new external information (meteorological forecast system output) can break the AUC ceiling.</p>
<p>Literature: Rebollo &amp; Balakrishnan (2014); Kim et al.&nbsp;(2016)</p>
<hr>
</section>
</div>
<div id="tabset-1-8" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-8-tab">
<section id="v10-target-encoding-network-weather-proxy" class="level3">
<h3 class="anchored" data-anchor-id="v10-target-encoding-network-weather-proxy">V10: Target Encoding + Network Weather Proxy</h3>
<p><strong>Target Encoding</strong>: Replace dest_airport, gate, subfleet label encoding with sklearn TargetEncoder(cv=5).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Negative reason</strong>: XGBoost depth=10 is already effective enough with label encoding; TE advantages are mainly seen in linear models and shallow trees (Pargent et al.&nbsp;2022).</p>
</div>
</div>
<p><strong>Network Weather Proxy</strong>: Average weather severity across 9 major Hub airports (ATL, ORD, DEN, LAX, CLT, JFK, SFO, EWR, LAS).</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V10 Best AUC = 0.7429 (−0.0011 vs V9)</strong></p>
<p>Network proxy reason: Existing DFW congestion features already capture local delay status; remote Hub weather impact on DFW is too weak within the T-2h window.</p>
</div>
</div>
<hr>
</section>
<section id="v11-notears-dag-3-model-oof-stacking" class="level3">
<h3 class="anchored" data-anchor-id="v11-notears-dag-3-model-oof-stacking">V11: NOTEARS DAG + 3-Model OOF Stacking</h3>
<p><strong>NOTEARS DAG</strong>: Use continuous optimization to learn causal graphs, add features from same causal clusters to XGBoost’s interaction_constraints.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Fatal issue: Linear NOTEARS found 0 edges from any feature to delayed_15.</strong></p>
<p>Markov Blanket is empty; interaction_constraints severely restrict XGBoost’s learning ability. XGB_DAG AUC plummeted to 0.6793 in T-2h+Enhanced (vs V9’s 0.7440, a 0.065 gap).</p>
</div>
</div>
<p><strong>3-Model OOF Stacking</strong>: XGBoost + CatBoost + LightGBM, logistic regression meta-learner.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V11 Best AUC = 0.7414 (−0.0026 vs V9)</strong></p>
<p>Three GBDT models are too correlated; Stacking cannot benefit from complementarity. LightGBM received negative weight in the meta-learner.</p>
</div>
</div>
<hr>
</section>
<section id="v12-delay-absorption-meta-feature" class="level3">
<h3 class="anchored" data-anchor-id="v12-delay-absorption-meta-feature">V12: Delay-Absorption Meta-Feature</h3>
<p><strong>Inspiration</strong>: arXiv:2512.08197 (Li 2025, AUC=0.898, but relies on departure delay features)</p>
<p><strong>Design</strong>: Stage I CatBoost predicts “whether previous delay is absorbed” (absorb_label), Stage II adds absorb_score.</p>
<p>Stage I OOF AUC = <strong>0.6946</strong> (absorption label absorb=1 accounts for 69.5%)</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>V12 Best AUC = 0.7423 (−0.0017 vs V9)</strong></p>
<p>Stage I quality insufficient; 8 input features (turnaround_min, etc.) already exist directly in V9 feature set — Stage I is just nonlinear reorganization, not new information. Li (2025)’s high AUC relies on departure delay features (leakage); our strict version cannot replicate.</p>
</div>
</div>
<p><strong>V9 confirmed as the best model across all 12 versions (AUC = 0.7440).</strong></p>
<hr>
</section>
</div>
<div id="tabset-1-9" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-9-tab">
<section id="issue-discovery" class="level3">
<h3 class="anchored" data-anchor-id="issue-discovery">Issue Discovery</h3>
<p>V9’s tail chain uses scheduled turnaround thresholds to determine “whether the previous flight has arrived” — but this judgment has a subtle leakage risk: at prediction time (T-2h), some previous flights haven’t actually arrived but are incorrectly marked as arrived.</p>
</section>
<section id="fix" class="level3">
<h3 class="anchored" data-anchor-id="fix">Fix</h3>
<p>Changed to using <strong>actual arrival time</strong> instead of scheduled time to determine tail chain availability.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 54%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Impact Scope</th>
<th>Proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>T-2h version affected flights</td>
<td><strong>1.04%</strong></td>
</tr>
<tr class="even">
<td>T-24h version affected flights</td>
<td>77.9% (→ T-24h version permanently deprecated)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>V9c Final AUC = 0.7418</strong> (−0.0022 vs V9, only 1.04% flights affected)</p>
<p>V9c became Gen2’s official finalized version, the foundation for all subsequent analyses (Phases 1–4).</p>
</div>
</div>
</div>
<hr>
</section>
<section id="v9d-right-censored-tail-chain-research-use" class="level3">
<h3 class="anchored" data-anchor-id="v9d-right-censored-tail-chain-research-use">V9d: Right-Censored Tail Chain (Research Use)</h3>
<p>V9d further changes tail chain from “previous arrived → use actual delay, not arrived → use 0” to <strong>right-censoring</strong>, using 7 features to encode “known partial information when previous flight hasn’t arrived” (overtime minutes, estimated remaining time, etc.), NaN for “unknowable at this time.”</p>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>V9d Temporal AUC = 0.7291</strong> (vs V9c 0.7418, −0.0127)</p>
<p>Random split AUC = <strong>0.7760</strong> (+0.047), the gap reconfirms the importance of temporal splitting.</p>
</div>
</div>
</div>
<p>V9d is used for Phase 1–4 comprehensive analysis (43 features, including 7 right-censored tail chain features).</p>
<hr>
</section>
</div>
<div id="tabset-1-10" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-10-tab">
<section id="phase-1-literature-leakage-audit" class="level3">
<h3 class="anchored" data-anchor-id="phase-1-literature-leakage-audit">Phase 1: Literature Leakage Audit</h3>
<p>Systematic review of data leakage across 12 published papers:</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Using temporal split</td>
<td>2/12 (16.7%)</td>
</tr>
<tr class="even">
<td>Completely clean features</td>
<td>2/12 (16.7%)</td>
</tr>
<tr class="odd">
<td>Severe or fatal leakage</td>
<td>5/12 (41.7%)</td>
</tr>
<tr class="even">
<td>Leaked papers reported AUC</td>
<td>0.87–0.99</td>
</tr>
<tr class="odd">
<td>Strict temporal studies reported AUC</td>
<td>0.62–0.74</td>
</tr>
</tbody>
</table>
<p><strong>Conclusion: Our temporal AUC = 0.7291 (V9d) is competitive under methodologically strict conditions.</strong></p>
</div>
</div>
<hr>
</section>
<section id="phase-2-literature-method-replication" class="level3">
<h3 class="anchored" data-anchor-id="phase-2-literature-method-replication">Phase 2: Literature Method Replication</h3>
<p>Replicated 6 literature methods under identical temporal split + V9d features (bootstrap 95% CI):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 15%">
<col style="width: 25%">
<col style="width: 9%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>AUC</th>
<th>95% CI</th>
<th>Δ</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>XGBoost (V6 Optuna) ★</strong></td>
<td><strong>0.7291</strong></td>
<td>[0.7257, 0.7323]</td>
<td>—</td>
<td>Baseline</td>
</tr>
<tr class="even">
<td>SMOTE + XGBoost</td>
<td>0.7015</td>
<td>[0.6981, 0.7048]</td>
<td>−0.0276</td>
<td>❌</td>
</tr>
<tr class="odd">
<td>ADASYN + XGBoost</td>
<td>0.7003</td>
<td>[0.6970, 0.7035]</td>
<td>−0.0288</td>
<td>❌</td>
</tr>
<tr class="even">
<td>SelectKBest + XGBoost</td>
<td>0.7062</td>
<td>[0.7029, 0.7094]</td>
<td>−0.0229</td>
<td>❌</td>
</tr>
<tr class="odd">
<td>FSFS + XGBoost</td>
<td>0.7108</td>
<td>[0.7075, 0.7140]</td>
<td>−0.0183</td>
<td>❌</td>
</tr>
<tr class="even">
<td><strong>LightGBM</strong></td>
<td><strong>0.7367</strong></td>
<td><strong>[0.7334, 0.7398]</strong></td>
<td><strong>+0.0076</strong></td>
<td>✅</td>
</tr>
<tr class="odd">
<td>ATT-BI-LSTM</td>
<td>0.7014</td>
<td>[0.6980, 0.7047]</td>
<td>−0.0277</td>
<td>❌</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>LightGBM significantly outperforms XGBoost (CIs non-overlapping)</strong>, but GBDT overall substantially outperforms deep learning, supporting the Aeolus benchmark (NeurIPS 2025) conclusion.</p>
</div>
</div>
<p>SMOTE/ADASYN failure reason: XGBoost scale_pos_weight is already sufficient; oversampling introduces synthetic noise in feature spaces with NaN.</p>
<hr>
</section>
<section id="phase-3-shap-feature-importance-analysis-v9d-43-features" class="level3">
<h3 class="anchored" data-anchor-id="phase-3-shap-feature-importance-analysis-v9d-43-features">Phase 3: SHAP Feature Importance Analysis (V9d, 43 features)</h3>
<p><strong>Top 10 Individual Features (mean |SHAP|):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 29%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th>Feature</th>
<th></th>
<th>SHAP</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>prev_arr_delay_known</td>
<td>0.0592</td>
<td>Right-censored tail chain <strong>[Our contribution]</strong></td>
</tr>
<tr class="even">
<td>2</td>
<td>dep_month</td>
<td>0.0536</td>
<td>Schedule (BTS)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>subfleet_encoded</td>
<td>0.0487</td>
<td>Aircraft/Infrastructure</td>
</tr>
<tr class="even">
<td>4</td>
<td>dep_hour</td>
<td>0.0383</td>
<td>Schedule (BTS)</td>
</tr>
<tr class="odd">
<td>5</td>
<td>prev_turnaround_avail</td>
<td>0.0333</td>
<td>Right-censored tail chain <strong>[Our contribution]</strong></td>
</tr>
<tr class="even">
<td>6</td>
<td>dfw_dep_count_1h</td>
<td>0.0301</td>
<td>Aircraft/Infrastructure</td>
</tr>
<tr class="odd">
<td>7</td>
<td>taf_dfw_ceiling_ft</td>
<td>0.0291</td>
<td>TAF Forecast <strong>[New]</strong></td>
</tr>
<tr class="even">
<td>8</td>
<td>is_holiday_period</td>
<td>0.0235</td>
<td>Schedule (BTS)</td>
</tr>
<tr class="odd">
<td>9</td>
<td>wx_pressure_hpa</td>
<td>0.0219</td>
<td>DFW METAR</td>
</tr>
<tr class="even">
<td>10</td>
<td>prev2_arr_delay_known</td>
<td>0.0213</td>
<td>Right-censored tail chain <strong>[Our contribution]</strong></td>
</tr>
</tbody>
</table>
<p><strong>By Data Source Group (SHAP Percentage):</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 22%">
<col style="width: 6%">
<col style="width: 20%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Source</th>
<th>Total SHAP</th>
<th>%</th>
<th>Features</th>
<th>Per-Feature Avg</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Schedule (BTS)</td>
<td>0.1283</td>
<td>22.2%</td>
<td>7</td>
<td>0.0183</td>
</tr>
<tr class="even">
<td>Aircraft/Infrastructure</td>
<td>0.1184</td>
<td>20.5%</td>
<td>6</td>
<td>0.0197</td>
</tr>
<tr class="odd">
<td>DFW METAR (NOAA)</td>
<td>0.0832</td>
<td>14.4%</td>
<td>8</td>
<td>0.0104</td>
</tr>
<tr class="even">
<td><strong>Right-censored tail chain [Ours]</strong></td>
<td><strong>0.1312</strong></td>
<td><strong>22.7%</strong></td>
<td><strong>7</strong></td>
<td><strong>0.0187</strong></td>
</tr>
<tr class="odd">
<td><strong>TAF Forecast [New]</strong></td>
<td><strong>0.0714</strong></td>
<td><strong>12.4%</strong></td>
<td><strong>9</strong></td>
<td><strong>0.0079</strong></td>
</tr>
<tr class="even">
<td><strong>Dest METAR [New]</strong></td>
<td><strong>0.0447</strong></td>
<td><strong>7.7%</strong></td>
<td><strong>6</strong></td>
<td><strong>0.0075</strong></td>
</tr>
</tbody>
</table>
<p><strong>Our three contributions combined: 42.8% (22.7% + 12.4% + 7.7%)</strong></p>
</div>
</div>
<hr>
</section>
<section id="phase-4-ablation-study" class="level3">
<h3 class="anchored" data-anchor-id="phase-4-ablation-study">Phase 4: Ablation Study</h3>
<p><strong>Incremental Addition:</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Step</th>
<th>Added Source</th>
<th>Features</th>
<th>AUC</th>
<th>Δ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Schedule (BTS)</td>
<td>7</td>
<td>0.6226</td>
<td>—</td>
</tr>
<tr class="even">
<td>2</td>
<td>+ Aircraft/Infrastructure</td>
<td>13</td>
<td>0.6710</td>
<td>+0.0484</td>
</tr>
<tr class="odd">
<td>3</td>
<td>+ DFW METAR</td>
<td>21</td>
<td>0.6928</td>
<td>+0.0218</td>
</tr>
<tr class="even">
<td>4</td>
<td>+ Dest METAR [New]</td>
<td>27</td>
<td>0.7048</td>
<td>+0.0120</td>
</tr>
<tr class="odd">
<td>5</td>
<td>+ TAF Forecast [New]</td>
<td>36</td>
<td>0.6969</td>
<td><strong>−0.0079</strong></td>
</tr>
<tr class="even">
<td>6</td>
<td>+ Right-censored tail chain [Ours]</td>
<td>43</td>
<td>0.7279</td>
<td><strong>+0.0311</strong></td>
</tr>
</tbody>
</table>
<p><strong>Leave-One-Source-Out:</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>Removed Source</th>
<th>AUC</th>
<th>Δ</th>
<th>Impact Level</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Full model</td>
<td>0.7279</td>
<td>—</td>
<td>—</td>
</tr>
<tr class="even">
<td>− Right-censored tail chain</td>
<td>0.6969</td>
<td><strong>−0.0311</strong></td>
<td><strong>Most critical</strong></td>
</tr>
<tr class="odd">
<td>− Aircraft/Infrastructure</td>
<td>0.7053</td>
<td>−0.0226</td>
<td>Critical</td>
</tr>
<tr class="even">
<td>− Schedule</td>
<td>0.7175</td>
<td>−0.0104</td>
<td>Moderate</td>
</tr>
<tr class="odd">
<td>− DFW METAR</td>
<td>0.7255</td>
<td>−0.0024</td>
<td>Marginal</td>
</tr>
<tr class="even">
<td>− Dest METAR</td>
<td><strong>0.7380</strong></td>
<td><strong>+0.0101</strong></td>
<td>Removal improves performance</td>
</tr>
<tr class="odd">
<td>− TAF Forecast</td>
<td>0.7285</td>
<td>+0.0006</td>
<td>Removal makes almost no difference</td>
</tr>
</tbody>
</table>
<p><strong>Tail chain is the most critical single source (removal −0.031) — this is our original contribution.</strong> Dest METAR and TAF interfere when combined (each effective alone, but redundant together).</p>
</div>
</div>
</section>
</div>
</div>
</div>
<hr>
<script>
window.addEventListener('DOMContentLoaded', function() {
  var hash = window.location.hash.replace('#', '');
  if (!hash) return;
  var tabs = document.querySelectorAll('[data-bs-toggle="tab"], [data-bs-toggle="pill"]');
  for (var i = 0; i < tabs.length; i++) {
    var target = tabs[i].getAttribute('data-bs-target') || tabs[i].getAttribute('href') || '';
    if (target.indexOf(hash) !== -1) {
      tabs[i].click();
      break;
    }
  }
});
</script>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>